apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: email-notifications
  namespace: promethus # Replace with your namespace
spec:
  route:
    receiver: email-receiver
    matchers:
    - name: alertname
      value: HighCPUUsage
    repeatInterval: 3h
  receivers:
  - name: email-receiver
    emailConfigs:
    - to: nourgroup5depi@gmail.com # Replace with your Gmail address
      from: nourgroup5depi@gmail.com # Replace with your Gmail address
      smarthost: smtp.gmail.com:587
      authIdentity: nourgroup5depi@gmail.com
      authUsername: nourgroup5depi@gmail.com # Replace with your Gmail address
      authPassword:
        name: password
        key:  pass       # Replace with your Gmail App Password
---
apiVersion: v1
kind: Secret
metadata:
  name: password
  namespace: promethus
data:
  pass: aW9ndyB2bHJ1IHNqb3YgYXlvYwo= #iogw vlru sjov ayoc