version: '3.8'
services:
  frontend:
    build: ./front-end
    container_name: my_frontend
    environment:
      API_URL: http://localhost:3000 # Change this URL dynamically
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    environment:
      DB_HOST: db  # Use the service name as the hostname
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: angular
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: angular
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - sql_data:/var/lib/db/sql_data

volumes:
  sql_data: